sudo: false
language: ruby
rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.6
  - 2.6.4
script:
  - bundle install
  - bundle exec rake
addons:
  apt:
    packages:
      - libonig-dev
cache:
  directories:
    - /home/travis/.rvm/
